# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BPT_Search' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BPT_Search
	
  pod 'SearchTextField'
  pod 'InstantSearchClient', '~> 7.0'

  target 'BPT_SearchTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'BPT_SearchUITests' do
    # Pods for testing
  end

end
